タイムゾーンを設定したい場合の前準備などをするタスクを追加
link-u/ansible-roles-v2_percona-cluster pull request #5
Opened 2020-10-13 21:14 UTC by y-hashida

### 変更点
#3 だけではタイムゾーンの設定をするには不十分なため, このような変更を追加
* my.cnf を作成する際に一部の変数を無効化するための機能を追加 (https://github.com/link-u/ansible-roles-v2_percona-cluster/commit/a4b24c477d96596df55b9ea58d5dcdd2c517c205).
* タイムゾーンを設定するためのテーブルをインポートするタスクを追加

### 参考
* https://dev.mysql.com/doc/refman/5.7/en/time-zone-support.html

2020-10-28 07:16 UTC, ledyba-z requested changes
おつ。やってること自体は大丈夫だと思うんだけど、
中々難しくなってきたので、解説とか書いといてもらえると助かる。

2020-10-28 07:16 UTC, ledyba-z commented on tasks/configure.yml
> +  when: item.value != None
これって
```
          ( __pxc_imported_timezone_table.stat.exists) | ternary({}, { 'default_time_zone': None } ),
```
でNoneに設定したのを反映させないようにしてるってことでおｋ？

2020-10-28 07:16 UTC, ledyba-z commented on templates/my.cnf.j2
> +{%   endif %}
if文が増えてきて、だんだん「どれがどのケースかわからん」という感じになってきたので、ifの分岐ごとに一行「stringのとき」とか「リストの時」とか「タイムゾーンを設定するためにNoneを設定した時」とかお気持ちを書いといてもらえると助かる

// いつもはプログラミング言語がそれをサポートしてくれるけど、
// Jinja2だと色々しょうがないのでコメントで…^^;

2020-10-28 07:16 UTC, ledyba-z commented on templates/my.cnf.j2
> +{%   if value != None %}
これもタイムゾーンを設定するために一時的にNoneに設定したケースを弾く用だよね？

2020-10-28 07:16 UTC, ledyba-z commented on tasks/add_timezone_table.yml
> +    - (__pxc_check_timezone.stdout_lines | length) == 0
純粋な質問なんだけど、タイムゾーンのテーブルって２回インポートするとヤバいの？
（あんまり無いと思うんだけど、インポート中に止ったとかしてテーブルが中途半端な状態になった時は、どうすればいいのかな〜と思った）

2020-10-28 10:07 UTC, y-hashida commented on tasks/add_timezone_table.yml
> +  command: "mysql -uroot -p{{ pxc_root_password }} -e 'SELECT * FROM mysql.time_zone_name;' -B"
空白のパスワードは盲点でしたｗ
ちなみにパスワードの部分ですが, `-p'{{ pxc_root_password }}'` だったりしませんか?

2020-10-28 10:18 UTC, y-hashida commented on tasks/configure.yml
> +  when: item.value != None
ですね！
`null` (Jinja2 では `None`) にした箇所は my.cnf からも排除するようになり, pxc のデフォルト値が採用されるのですが, mysql_variables モジュールではあくまでスキップするだけになっています.
(デフォルト値まで反映させるのが難しかったため)

2020-10-28 10:19 UTC, y-hashida commented on templates/my.cnf.j2
> +{%   endif %}
Jinja2 にもコメントを書く機能があるみたいなので, それで補足を入れてみようかと思います！
https://showa-yojyo.github.io/notebook/python-jinja2.html#id10

2020-10-28 10:21 UTC, y-hashida commented on templates/my.cnf.j2
> +{%   if value != None %}
そうです！
また, 「この role のデフォルト値を使いたくはなく, PXC のデフォルト値を使いたい」というときなどにも利用できます！
https://github.com/link-u/ansible-roles-v2_percona-cluster/blob/65e3039693ee00468a1526b4aa25e5a4c3bbc1d6/defaults/main.yml#L132-L165

2020-10-28 10:26 UTC, y-hashida commented on tasks/add_timezone_table.yml
> +    - (__pxc_check_timezone.stdout_lines | length) == 0
多分問題ないかもしれないです.
ただ ansible を流し込むたびに changed が発生するためあまり気持ちよくないというのと, 変更のない2度目の流し込みで changed が発生した時 ansible-ci が failed になるという懸念点があります；；

このタスクのみ changed を無効化することもできますが, 書き込みをする類のタスクなのであまり無効化にしたくないというお気持ちがあります.

もしかしたらですが, collection.mysql 内の ansible モジュールには冪等性を担保しつつ, DB をインポートする方法があるかもしれないのでその辺でなんとかできないか調べてみます！

2020-10-29 05:26 UTC, ledyba-z commented on tasks/add_timezone_table.yml
> +  command: "mysql -uroot -p{{ pxc_root_password }} -e 'SELECT * FROM mysql.time_zone_name;' -B"
どっちでも大丈夫。
```
program -p'aa bb'
```
って書いても
```
program '-paa bb'
```
って書いても、シェルがよしなにしてくれて、programのargv[1]は`-paa bb`になった…はず。

2020-10-29 05:32 UTC, y-hashida commented on tasks/add_timezone_table.yml
> +  command: "mysql -uroot -p{{ pxc_root_password }} -e 'SELECT * FROM mysql.time_zone_name;' -B"
なるほど！
たしかにあくまでシェルの引数としては `-phogehoe` という文字列でした！
ありがとうございます！

2020-10-29 06:21 UTC, ledyba-z commented on tasks/configure.yml
> +  when: item.value != None
おｋ、仮にgroup_varsで手動でnullに指定したら何も設定されず無視されるだけ、というのも挙動としてはおかしくないし良いと思う。

2020-10-29 06:21 UTC, ledyba-z commented on templates/my.cnf.j2
> +{%   endif %}
👍

2020-10-29 06:21 UTC, ledyba-z commented on templates/my.cnf.j2
> +{%   if value != None %}
あぁ、無視されてmy.cnfには書かれないから…ってことね。良いと思う。

2020-10-29 06:21 UTC, ledyba-z commented on tasks/add_timezone_table.yml
> +    - (__pxc_check_timezone.stdout_lines | length) == 0
たしかに、実質的に変更が無いのにchanagredが発生するのは精神衛生上よくないね…
// インポートした時にMySQLのテーブルの中身まで見て変化があるかないかチェックするのは無理だし…

了解、なら今のままでよいと思う。もう一度どうしてもインポートしたい時は手動でtableをdropするとかしてもいいはずやし…
（ついでに再インポートしたいというのは異常事態なのは間違いないから、それぐらいは手動で目視確認しといたほうが良さそう…）

2020-10-29 06:46 UTC, y-hashida commented on tasks/add_timezone_table.yml
> +    - (__pxc_check_timezone.stdout_lines | length) == 0
ありがとうございます！
今回のプルリクではここまでにしておいて, 余力があるときにうまくできないかまた考えてみます！

2020-10-29 09:16 UTC, y-hashida commented on templates/my.cnf.j2
> +{%   endif %}
Jinja2 にてコメントを追記しました！

2020-10-29 09:19 UTC, y-hashida commented
@ledyba-z 
以下の修正と追加をしました！
* '-p{{ pxc_root_password }}' の箇所を修正しました.
* Jinja2 にて my.cnf.j2 にコメントを追記しました.
* mysql_variable シナリオにて, pxc_root_password に半角スペースを含ませました.
* mysql_timezone シナリオを用意し, timezone の設定を CI するようにしました.

2020-10-29 09:45 UTC, ledyba-z approved these changes
@y-hashida 

LGTM。修正ありがとう👍 

''で囲うのをやめてquoteフィルタ使ってみるもヨシ、そのままマージするもヨシという感じで、Approveは出すけれどマージはしないままにしときます

2020-10-29 09:45 UTC, ledyba-z commented on templates/my.cnf.j2
> +{%   endif %}
👍

2020-10-29 09:45 UTC, ledyba-z commented on tasks/add_timezone_table.yml
> +  command: "mysql -uroot '-p{{ pxc_root_password }}' -e 'SELECT * FROM mysql.time_zone_name;' -B"
今回はオーバーキル気味だし流石に良いかなという感じもするけど、Jinja2の quoteというフィルタを使うとさらに安全にシェルコマンドが生成できるのを発見した。やるとしたらこうかな。

```bash
-p{{ pxc_root_password | quote }}
```

ドキュメント：[Jinja2 filters — Ansible Documentation](https://ansible-docs.readthedocs.io/zh/stable-2.0/rst/playbooks_filters.html#other-useful-filters)

ぶっちゃけ任意のユーザーの任意の入力を受付けるわけじゃあないから、あんまり頑張っても仕方のないところなのでどうするかは任せますわ
（逆に悪意のある人がやってくるかもしれない所はこういう所は執拗なぐらいに慎重にならないとアカン）

2020-10-29 10:02 UTC, y-hashida commented on tasks/add_timezone_table.yml
> +  command: "mysql -uroot '-p{{ pxc_root_password }}' -e 'SELECT * FROM mysql.time_zone_name;' -B"
なるほど！
せっかくなので `quote` フィルターを使ってみます！
CI が通ればマージしますね！

2020-10-29 10:27 UTC, merged